/* =====================================================================
   SearchPV Listing Attribute Subsystem
   PostgreSQL / Supabase compatible

   Existing dependency:
       dw.lstng(lstng_ky, lstng_nb)

   Current-state model only. No attribute history is retained.
   ===================================================================== */

BEGIN;

CREATE SCHEMA IF NOT EXISTS dw;
CREATE SCHEMA IF NOT EXISTS stg;

CREATE TABLE IF NOT EXISTS dw.attribute_data_type_lu
(
    attribute_data_type_cd text PRIMARY KEY,
    attribute_data_type_nm text NOT NULL,
    attribute_data_type_ds text,
    active_fl boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS dw.attribute_category
(
    attribute_category_cd text PRIMARY KEY,
    attribute_category_nm text NOT NULL,
    attribute_category_ds text,
    display_order_nb smallint,
    active_fl boolean NOT NULL DEFAULT true,
    load_dt timestamptz NOT NULL DEFAULT now(),
    update_dt timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dw.attribute_unit_lu
(
    attribute_unit_cd text PRIMARY KEY,
    attribute_unit_nm text NOT NULL,
    attribute_unit_ds text,
    active_fl boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS dw.attribute
(
    attribute_ky bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribute_category_cd text NOT NULL,
    attribute_cd text NOT NULL,
    attribute_nm text NOT NULL,
    attribute_ds text,
    attribute_data_type_cd text NOT NULL,
    default_unit_cd text,
    filterable_fl boolean NOT NULL DEFAULT true,
    displayable_fl boolean NOT NULL DEFAULT true,
    ai_searchable_fl boolean NOT NULL DEFAULT true,
    repeatable_fl boolean NOT NULL DEFAULT false,
    active_fl boolean NOT NULL DEFAULT true,
    display_order_nb smallint,
    load_dt timestamptz NOT NULL DEFAULT now(),
    update_dt timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT attribute_cd_uq UNIQUE (attribute_cd),
    CONSTRAINT attribute_category_fk
        FOREIGN KEY (attribute_category_cd)
        REFERENCES dw.attribute_category(attribute_category_cd),
    CONSTRAINT attribute_data_type_fk
        FOREIGN KEY (attribute_data_type_cd)
        REFERENCES dw.attribute_data_type_lu(attribute_data_type_cd),
    CONSTRAINT attribute_default_unit_fk
        FOREIGN KEY (default_unit_cd)
        REFERENCES dw.attribute_unit_lu(attribute_unit_cd)
);

CREATE TABLE IF NOT EXISTS dw.attribute_option
(
    attribute_option_ky bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribute_ky bigint NOT NULL,
    attribute_option_cd text NOT NULL,
    attribute_option_nm text NOT NULL,
    attribute_option_ds text,
    display_order_nb smallint,
    active_fl boolean NOT NULL DEFAULT true,
    load_dt timestamptz NOT NULL DEFAULT now(),
    update_dt timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT attribute_option_uq UNIQUE (attribute_ky, attribute_option_cd),
    CONSTRAINT attribute_option_attribute_fk
        FOREIGN KEY (attribute_ky)
        REFERENCES dw.attribute(attribute_ky)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dw.attribute_source
(
    attribute_source_ky bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribute_ky bigint NOT NULL,
    source_system_cd text NOT NULL DEFAULT 'MLS_CSV',
    source_column_nm text NOT NULL,
    source_section_nm text,
    source_field_nm text,
    source_path_tx text NOT NULL,
    source_priority_nb smallint NOT NULL DEFAULT 100,
    active_fl boolean NOT NULL DEFAULT true,
    load_dt timestamptz NOT NULL DEFAULT now(),
    update_dt timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT attribute_source_path_uq
        UNIQUE (source_system_cd, source_path_tx),
    CONSTRAINT attribute_source_attribute_fk
        FOREIGN KEY (attribute_ky)
        REFERENCES dw.attribute(attribute_ky)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dw.attribute_value_map
(
    attribute_value_map_ky bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribute_source_ky bigint NOT NULL,
    raw_value_tx text NOT NULL,
    normalized_option_ky bigint,
    normalized_boolean_fl boolean,
    normalized_number_nb numeric(18,6),
    normalized_amount_nb numeric(18,2),
    normalized_text_tx text,
    normalized_date_dt date,
    normalized_unit_cd text,
    normalization_status_cd text NOT NULL DEFAULT 'ACTIVE',
    confidence_nb numeric(5,4) NOT NULL DEFAULT 1.0000,
    reviewed_fl boolean NOT NULL DEFAULT false,
    active_fl boolean NOT NULL DEFAULT true,
    load_dt timestamptz NOT NULL DEFAULT now(),
    update_dt timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT attribute_value_map_uq
        UNIQUE (attribute_source_ky, raw_value_tx),
    CONSTRAINT attribute_value_map_source_fk
        FOREIGN KEY (attribute_source_ky)
        REFERENCES dw.attribute_source(attribute_source_ky)
        ON DELETE CASCADE,
    CONSTRAINT attribute_value_map_option_fk
        FOREIGN KEY (normalized_option_ky)
        REFERENCES dw.attribute_option(attribute_option_ky),
    CONSTRAINT attribute_value_map_unit_fk
        FOREIGN KEY (normalized_unit_cd)
        REFERENCES dw.attribute_unit_lu(attribute_unit_cd),
    CONSTRAINT attribute_value_map_status_ck
        CHECK (normalization_status_cd IN
            ('ACTIVE', 'PENDING_REVIEW', 'REJECTED', 'DEPRECATED')),
    CONSTRAINT attribute_value_map_typed_value_ck
        CHECK (num_nonnulls(
            normalized_option_ky,
            normalized_boolean_fl,
            normalized_number_nb,
            normalized_amount_nb,
            normalized_text_tx,
            normalized_date_dt
        ) <= 1),
    CONSTRAINT attribute_value_map_confidence_ck
        CHECK (confidence_nb BETWEEN 0 AND 1)
);

CREATE TABLE IF NOT EXISTS dw.lstng_attribute_value
(
    lstng_attribute_value_ky bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lstng_ky bigint NOT NULL,
    attribute_ky bigint NOT NULL,
    attribute_source_ky bigint NOT NULL,
    attribute_option_ky bigint,
    value_boolean_fl boolean,
    value_number_nb numeric(18,6),
    value_amount_nb numeric(18,2),
    value_text_tx text,
    value_date_dt date,
    raw_value_tx text NOT NULL,
    source_batch_number_tx text,
    load_dt timestamptz NOT NULL DEFAULT now(),
    update_dt timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT lstng_attribute_value_uq
        UNIQUE (lstng_ky, attribute_source_ky),
    CONSTRAINT lstng_attribute_value_lstng_fk
        FOREIGN KEY (lstng_ky)
        REFERENCES dw.lstng(lstng_ky)
        ON DELETE CASCADE,
    CONSTRAINT lstng_attribute_value_attribute_fk
        FOREIGN KEY (attribute_ky)
        REFERENCES dw.attribute(attribute_ky),
    CONSTRAINT lstng_attribute_value_source_fk
        FOREIGN KEY (attribute_source_ky)
        REFERENCES dw.attribute_source(attribute_source_ky),
    CONSTRAINT lstng_attribute_value_option_fk
        FOREIGN KEY (attribute_option_ky)
        REFERENCES dw.attribute_option(attribute_option_ky),
    CONSTRAINT lstng_attribute_value_typed_value_ck
        CHECK (num_nonnulls(
            attribute_option_ky,
            value_boolean_fl,
            value_number_nb,
            value_amount_nb,
            value_text_tx,
            value_date_dt
        ) <= 1)
);

CREATE TABLE IF NOT EXISTS dw.lstng_search_attribute
(
    lstng_ky bigint PRIMARY KEY,

    furnished_cd text,
    pet_friendly_fl boolean,
    preconstruction_fl boolean,
    flex_room_fl boolean,
    master_planned_community_fl boolean,

    beachfront_fl boolean,
    oceanfront_fl boolean,
    waterfront_fl boolean,
    beach_access_fl boolean,

    ocean_view_fl boolean,
    mountain_view_fl boolean,
    city_view_fl boolean,
    marina_view_fl boolean,
    golf_view_fl boolean,
    pool_view_fl boolean,
    garden_view_fl boolean,
    jungle_view_fl boolean,

    pool_fl boolean,
    private_pool_fl boolean,
    common_pool_fl boolean,
    infinity_pool_fl boolean,
    jacuzzi_fl boolean,
    gym_fl boolean,
    spa_fl boolean,

    elevator_fl boolean,
    security_24hr_fl boolean,
    gated_fl boolean,
    wheelchair_accessible_fl boolean,

    fiber_optic_fl boolean,
    air_conditioning_fl boolean,
    washer_dryer_fl boolean,
    solar_panels_fl boolean,

    parking_fl boolean,
    parking_type_cd text,
    parking_space_nb smallint,

    hoa_monthly_mxn_amt numeric(14,2),
    hoa_monthly_usd_amt numeric(14,2),
    hoa_includes_water_fl boolean,
    hoa_includes_electricity_fl boolean,
    hoa_includes_gas_fl boolean,

    source_batch_number_tx text,
    derived_dt timestamptz NOT NULL DEFAULT now(),
    update_dt timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT lstng_search_attribute_lstng_fk
        FOREIGN KEY (lstng_ky)
        REFERENCES dw.lstng(lstng_ky)
        ON DELETE CASCADE,
    CONSTRAINT lstng_search_attribute_furnished_ck
        CHECK (furnished_cd IS NULL OR furnished_cd IN
            ('FURNISHED', 'PARTIALLY_FURNISHED', 'UNFURNISHED'))
);

CREATE INDEX IF NOT EXISTS attribute_category_ix
    ON dw.attribute(attribute_category_cd);
CREATE INDEX IF NOT EXISTS attribute_source_attribute_ix
    ON dw.attribute_source(attribute_ky);
CREATE INDEX IF NOT EXISTS lstng_attribute_value_lstng_ix
    ON dw.lstng_attribute_value(lstng_ky);
CREATE INDEX IF NOT EXISTS lstng_attribute_value_attribute_ix
    ON dw.lstng_attribute_value(attribute_ky);
CREATE INDEX IF NOT EXISTS lstng_attribute_value_option_ix
    ON dw.lstng_attribute_value(attribute_option_ky)
    WHERE attribute_option_ky IS NOT NULL;

CREATE INDEX IF NOT EXISTS lstng_search_attribute_beachfront_ix
    ON dw.lstng_search_attribute(lstng_ky) WHERE beachfront_fl IS TRUE;
CREATE INDEX IF NOT EXISTS lstng_search_attribute_oceanfront_ix
    ON dw.lstng_search_attribute(lstng_ky) WHERE oceanfront_fl IS TRUE;
CREATE INDEX IF NOT EXISTS lstng_search_attribute_pet_ix
    ON dw.lstng_search_attribute(lstng_ky) WHERE pet_friendly_fl IS TRUE;
CREATE INDEX IF NOT EXISTS lstng_search_attribute_pool_ix
    ON dw.lstng_search_attribute(lstng_ky) WHERE pool_fl IS TRUE;
CREATE INDEX IF NOT EXISTS lstng_search_attribute_elevator_ix
    ON dw.lstng_search_attribute(lstng_ky) WHERE elevator_fl IS TRUE;
CREATE INDEX IF NOT EXISTS lstng_search_attribute_parking_ix
    ON dw.lstng_search_attribute(lstng_ky) WHERE parking_fl IS TRUE;

CREATE OR REPLACE VIEW dw.v_lstng_attribute_detail AS
SELECT
    lav.lstng_attribute_value_ky,
    lav.lstng_ky,
    l.lstng_nb,
    a.attribute_category_cd,
    a.attribute_cd,
    a.attribute_nm,
    a.attribute_data_type_cd,
    ao.attribute_option_cd,
    ao.attribute_option_nm,
    lav.value_boolean_fl,
    lav.value_number_nb,
    lav.value_amount_nb,
    lav.value_text_tx,
    lav.value_date_dt,
    lav.raw_value_tx,
    s.source_path_tx,
    lav.source_batch_number_tx,
    lav.load_dt,
    lav.update_dt
FROM dw.lstng_attribute_value lav
JOIN dw.lstng l ON l.lstng_ky = lav.lstng_ky
JOIN dw.attribute a ON a.attribute_ky = lav.attribute_ky
JOIN dw.attribute_source s ON s.attribute_source_ky = lav.attribute_source_ky
LEFT JOIN dw.attribute_option ao ON ao.attribute_option_ky = lav.attribute_option_ky;

INSERT INTO dw.attribute_data_type_lu
(attribute_data_type_cd, attribute_data_type_nm, attribute_data_type_ds)
VALUES
    ('BOOLEAN', 'Boolean', 'Explicit true, false, or unknown.'),
    ('NUMBER',  'Number',  'General numeric value.'),
    ('AMOUNT',  'Amount',  'Currency or monetary amount.'),
    ('DATE',    'Date',    'Calendar date.'),
    ('TEXT',    'Text',    'Free or semi-structured text.'),
    ('OPTION',  'Option',  'Controlled categorical value.')
ON CONFLICT (attribute_data_type_cd) DO UPDATE SET
    attribute_data_type_nm = EXCLUDED.attribute_data_type_nm,
    attribute_data_type_ds = EXCLUDED.attribute_data_type_ds,
    active_fl = true;

INSERT INTO dw.attribute_unit_lu
(attribute_unit_cd, attribute_unit_nm, attribute_unit_ds)
VALUES
    ('MXN', 'Mexican pesos', 'Mexican peso amount.'),
    ('USD', 'US dollars', 'United States dollar amount.'),
    ('M', 'Meters', 'Linear meters.'),
    ('M2', 'Square meters', 'Area in square meters.'),
    ('FT2', 'Square feet', 'Area in square feet.'),
    ('COUNT', 'Count', 'Whole or fractional count.')
ON CONFLICT (attribute_unit_cd) DO UPDATE SET
    attribute_unit_nm = EXCLUDED.attribute_unit_nm,
    attribute_unit_ds = EXCLUDED.attribute_unit_ds,
    active_fl = true;

COMMIT;
