insert into content.page_content (
    content_type,
    entity_type,
    entity_slug,
    zone_slug,
    area_slug,
    community_slug,
    title,
    body,
    sort_order,
    active_fl
)
values
(
    'description',
    'area',
    'chapala',
    'guadalajara',
    'chapala',
    null,
    'About Chapala',
    'Chapala and the Lake Chapala area offer a lakeside lifestyle with a quieter pace, established expat communities, restaurants, cafes, and scenic mountain and lake views. Beach access is not relevant here, but buyers are often drawn to the climate, walkable village centers, single-family homes, small condominium projects, and value compared with coastal resort markets.',
    1,
    true
),
(
    'description',
    'area',
    'guadalajara',
    'guadalajara',
    'guadalajara',
    null,
    'About Guadalajara',
    'Guadalajara is a major metropolitan market with urban neighborhoods, restaurants, nightlife, shopping, hospitals, universities, and business services. Housing stock ranges from traditional homes and apartments to modern vertical condominium developments, attracting local professionals, investors, families, and buyers seeking city convenience rather than beach access.',
    1,
    true
),
(
    'description',
    'area',
    'zapopan',
    'guadalajara',
    'zapopan',
    null,
    'About Zapopan',
    'Zapopan is one of the Guadalajara area''s strongest residential and commercial markets, with upscale neighborhoods, shopping centers, restaurants, business districts, and modern condominium development. Buyers often include families, professionals, investors, and residents seeking suburban comfort with access to metropolitan amenities.',
    1,
    true
),
(
    'description',
    'area',
    'other',
    'other',
    'other',
    null,
    'About Other',
    'This category captures properties that do not fit cleanly into the main regional area groupings. Housing stock, buyer profiles, amenities, and beach access vary widely, so buyers should review individual communities and listings carefully.',
    1,
    true
),
(
    'description',
    'area',
    'airport',
    'puerto-vallarta',
    'airport',
    null,
    'About Airport',
    'The Airport area offers practical access to Puerto Vallarta''s airport, main highways, shopping, services, and residential neighborhoods. It is generally less focused on nightlife or beach lifestyle and more attractive to local residents, workers, investors, and buyers seeking convenience, value, and access to transportation corridors.',
    1,
    true
),
(
    'description',
    'area',
    'aramara',
    'puerto-vallarta',
    'aramara',
    null,
    'About Aramara',
    'Aramara is a centrally located Puerto Vallarta area with shopping, services, schools, local restaurants, and convenient access to the Hotel Zone, Marina, and main roads. Housing stock includes traditional homes, small condominium buildings, and newer infill projects, appealing to local families, long-term residents, and value-oriented buyers.',
    1,
    true
),
(
    'description',
    'area',
    'centro-north',
    'puerto-vallarta',
    'centro-north',
    null,
    'About Centro North',
    'Centro North offers a classic Puerto Vallarta setting with hillside streets, traditional homes, condominium buildings, restaurants, galleries, and access to downtown services. Beach access varies by neighborhood, but buyers are often drawn to views, walkability, character, and proximity to the Malecon and central city lifestyle.',
    1,
    true
),
(
    'description',
    'area',
    'centro-south',
    'puerto-vallarta',
    'centro-south',
    null,
    'About Centro South',
    'Centro South is one of Puerto Vallarta''s most recognized lifestyle and investment areas, including highly active neighborhoods near Zona Romantica, Amapas, Alta Vista, and Conchas Chinas. It is known for restaurants, nightlife, walkability, beach access, condominium development, vacation-rental demand, and strong interest from foreign buyers, retirees, and investors.',
    1,
    true
),
(
    'description',
    'area',
    'francisco-villa-east',
    'puerto-vallarta',
    'francisco-villa-east',
    null,
    'About Francisco Villa East',
    'Francisco Villa East is an inland residential area with local neighborhoods, services, shopping access, and generally more attainable pricing than the beach and downtown corridors. Housing stock includes homes, small multifamily buildings, and newer condominium options, attracting local families, long-term residents, and buyers seeking space and value.',
    1,
    true
),
(
    'description',
    'area',
    'francisco-villa-west',
    'puerto-vallarta',
    'francisco-villa-west',
    null,
    'About Francisco Villa West',
    'Francisco Villa West is a central Puerto Vallarta area with convenient access to shopping, restaurants, schools, medical services, and main transportation routes. It includes a mix of homes, condominiums, and infill development, appealing to full-time residents, investors, and buyers who want central convenience without paying beachfront premiums.',
    1,
    true
),
(
    'description',
    'area',
    'hotel-zone',
    'puerto-vallarta',
    'hotel-zone',
    null,
    'About Hotel Zone',
    'Puerto Vallarta''s Hotel Zone is a major beachfront and condominium corridor with hotels, shopping centers, restaurants, beach clubs, and easy access to downtown and the airport. Housing stock is heavily weighted toward condominiums, including resort-style towers and vacation-oriented projects, attracting second-home buyers, investors, and seasonal residents.',
    1,
    true
),
(
    'description',
    'area',
    'ixtapa',
    'puerto-vallarta',
    'ixtapa',
    null,
    'About Ixtapa',
    'Ixtapa is an inland residential area northeast of central Puerto Vallarta, offering local neighborhoods, services, schools, and more value-oriented housing. Beach access is indirect, but the area appeals to local families, long-term residents, and buyers seeking larger homes or lower entry prices compared with coastal neighborhoods.',
    1,
    true
),
(
    'description',
    'area',
    'libramiento-ne',
    'puerto-vallarta',
    'libramiento-ne',
    null,
    'About Libramiento NE',
    'Libramiento NE includes neighborhoods along and near the bypass road, with convenient access between downtown, hillside areas, and inland Puerto Vallarta. Housing stock can include homes, small condominium buildings, and view-oriented properties, attracting buyers who value access, views, and pricing outside the primary beach corridors.',
    1,
    true
),
(
    'description',
    'area',
    'marina',
    'puerto-vallarta',
    'marina',
    null,
    'About Marina',
    'The Marina area is centered around Marina Vallarta and offers a planned resort-residential environment with restaurants, golf, boating, shops, and waterfront amenities. Housing stock includes condominiums, villas, and homes, appealing to retirees, boaters, seasonal residents, and buyers seeking a quieter, polished alternative to downtown.',
    1,
    true
),
(
    'description',
    'area',
    'mojoneras',
    'puerto-vallarta',
    'mojoneras',
    null,
    'About Mojoneras',
    'Mojoneras is an inland Puerto Vallarta area with local residential neighborhoods, services, and access to major roads. It is generally more practical than resort-focused, attracting local families, workers, and buyers seeking affordability, space, and proximity to employment and transportation corridors.',
    1,
    true
),
(
    'description',
    'area',
    'pitillal-north',
    'puerto-vallarta',
    'pitillal-north',
    null,
    'About Pitillal North',
    'Pitillal North offers local residential neighborhoods, schools, shopping, and access to everyday services in one of Puerto Vallarta''s established inland districts. Housing stock is mostly homes and small multifamily properties, with buyers often focused on value, family living, and long-term occupancy rather than beach proximity.',
    1,
    true
),
(
    'description',
    'area',
    'pitillal-south',
    'puerto-vallarta',
    'pitillal-south',
    null,
    'About Pitillal South',
    'Pitillal South is a local residential area with convenient access to shopping, services, and central Puerto Vallarta. It offers a mix of homes, small condominium options, and practical urban housing, appealing to local residents, investors, and buyers seeking affordability within the city.',
    1,
    true
),
(
    'description',
    'area',
    'progresso-universida',
    'puerto-vallarta',
    'progresso-universida',
    null,
    'About Progresso/Universida',
    'Progresso/Universida is an inland Puerto Vallarta area near schools, services, and developing residential neighborhoods. It tends to offer practical housing options and value compared with beachside markets, attracting local families, students, workers, and long-term residents.',
    1,
    true
),
(
    'description',
    'area',
    'south-shore',
    'puerto-vallarta',
    'south-shore',
    null,
    'About South Shore',
    'The South Shore is known for dramatic coastline, jungle-covered hillsides, ocean views, beaches, and luxury homes and condominiums. Restaurants and nightlife are more limited than downtown, but buyers are drawn to privacy, views, resort-style living, and access to beaches and communities south of Puerto Vallarta.',
    1,
    true
),
(
    'description',
    'area',
    'bucerias',
    'riviera-nayarit',
    'bucerias',
    null,
    'About Bucerias',
    'Bucerias is one of Riviera Nayarit''s most established coastal towns, with a walkable center, restaurants, beach clubs, galleries, and a growing condominium market. Housing stock includes homes, low-rise condos, beachfront projects, and new developments, attracting retirees, vacation-home buyers, investors, and full-time residents.',
    1,
    true
),
(
    'description',
    'area',
    'costa-banderas',
    'riviera-nayarit',
    'costa-banderas',
    null,
    'About Costa Banderas',
    'Costa Banderas includes smaller coastal and inland communities within Riviera Nayarit, with a mix of beach access, local neighborhoods, and emerging development. Buyers are often seeking value, lifestyle, and growth potential compared with more established resort markets.',
    1,
    true
),
(
    'description',
    'area',
    'destiladeras',
    'riviera-nayarit',
    'destiladeras',
    null,
    'About Destiladeras',
    'Destiladeras is known for beautiful beach frontage, lower-density surroundings, and proximity to Punta de Mita and La Cruz. Housing stock is limited and often oriented toward luxury, land, or boutique coastal development, attracting buyers seeking beach access, privacy, and long-term upside.',
    1,
    true
),
(
    'description',
    'area',
    'flamingos',
    'riviera-nayarit',
    'flamingos',
    null,
    'About Flamingos',
    'Flamingos is a planned Riviera Nayarit resort-residential area with condominium towers, golf, beach access, and proximity to Bucerias and Nuevo Vallarta. It attracts vacation-home buyers, retirees, and investors seeking newer condo developments, resort amenities, and a quieter beach lifestyle.',
    1,
    true
),
(
    'description',
    'area',
    'guayabitos',
    'riviera-nayarit',
    'guayabitos',
    null,
    'About Guayabitos',
    'Guayabitos is a traditional beach-town market on the northern Riviera Nayarit coast, known for family tourism, beach access, local restaurants, and a relaxed atmosphere. Housing includes homes, small condos, hotels, and investment properties, attracting domestic buyers, retirees, and lifestyle investors.',
    1,
    true
),
(
    'description',
    'area',
    'jarretaderas',
    'riviera-nayarit',
    'jarretaderas',
    null,
    'About Jarretaderas',
    'Jarretaderas is an inland community near Nuevo Vallarta, Vidanta, and major resort corridors. It offers local services, growing residential development, and access to employment centers, attracting local families, investors, and buyers looking for value close to the Riviera Nayarit resort market.',
    1,
    true
),
(
    'description',
    'area',
    'la-cruz-de-hunanacax',
    'riviera-nayarit',
    'la-cruz-de-hunanacax',
    null,
    'About La Cruz de Hunanacax',
    'La Cruz is a coastal village and marina market known for boating, seafood restaurants, live music, a relaxed village atmosphere, and access to nearby beaches. Housing stock includes homes, condominiums, and view properties, attracting boaters, retirees, second-home buyers, and lifestyle investors.',
    1,
    true
),
(
    'description',
    'area',
    'litibu',
    'riviera-nayarit',
    'litibu',
    null,
    'About Litibu',
    'Litibu is a quieter coastal and golf-oriented area near Punta de Mita, offering beach access, resort surroundings, and lower-density development. Housing is often oriented toward luxury homes, condominiums, and land opportunities, appealing to buyers seeking privacy, nature, and proximity to premium Riviera Nayarit destinations.',
    1,
    true
),
(
    'description',
    'area',
    'lo-de-marcos',
    'riviera-nayarit',
    'lo-de-marcos',
    null,
    'About Lo de Marcos',
    'Lo de Marcos is a small coastal town with a relaxed beach lifestyle, local restaurants, and a quieter atmosphere than nearby Sayulita or San Pancho. Housing includes homes, small rental properties, and limited condominium options, attracting lifestyle buyers, retirees, and investors seeking a slower pace.',
    1,
    true
),
(
    'description',
    'area',
    'mezcales',
    'riviera-nayarit',
    'mezcales',
    null,
    'About Mezcales',
    'Mezcales is an inland Riviera Nayarit area with local services, shopping access, and proximity to Nuevo Vallarta, Bucerias, and the airport corridor. Housing includes homes, gated communities, and value-oriented development, attracting local families, workers, and buyers seeking affordability near resort markets.',
    1,
    true
),
(
    'description',
    'area',
    'nayarit-costa-norte',
    'riviera-nayarit',
    'nayarit-costa-norte',
    null,
    'About Nayarit Costa Norte',
    'Nayarit Costa Norte covers northern coastal markets with a mix of beach towns, rural settings, and emerging development. Buyer interest often centers on lifestyle, land, beach access, and long-term growth potential, with housing stock varying widely by community.',
    1,
    true
),
(
    'description',
    'area',
    'nuevo-vallarta-east',
    'riviera-nayarit',
    'nuevo-vallarta-east',
    null,
    'About Nuevo Vallarta East',
    'Nuevo Vallarta East is an inland and residential extension of the Nuevo Vallarta market, with access to services, gated communities, and resort employment centers. Housing includes homes, condos, and planned developments, attracting families, retirees, and buyers seeking value near the beach and resort corridor.',
    1,
    true
),
(
    'description',
    'area',
    'nuevo-vallarta-west',
    'riviera-nayarit',
    'nuevo-vallarta-west',
    null,
    'About Nuevo Vallarta West',
    'Nuevo Vallarta West is a major resort and residential market with beach access, marina areas, golf, gated communities, and condominium developments. It attracts retirees, vacation-home buyers, investors, and families seeking resort amenities, newer inventory, and proximity to the airport.',
    1,
    true
),
(
    'description',
    'area',
    'punta-de-mita',
    'riviera-nayarit',
    'punta-de-mita',
    null,
    'About Punta de Mita',
    'Punta de Mita is one of Riviera Nayarit''s premier luxury markets, known for beaches, resort communities, golf, surfing, and high-end homes and condominiums. Buyers are often affluent second-home owners, investors, and lifestyle buyers seeking privacy, amenities, and premium coastal real estate.',
    1,
    true
),
(
    'description',
    'area',
    'san-pancho',
    'riviera-nayarit',
    'san-pancho',
    null,
    'About San Pancho',
    'San Pancho offers a relaxed coastal village lifestyle with restaurants, arts, community events, beach access, and a quieter feel than Sayulita. Housing includes homes, boutique condos, and view properties, attracting lifestyle buyers, retirees, families, and investors seeking character and community.',
    1,
    true
),
(
    'description',
    'area',
    'sayulita',
    'riviera-nayarit',
    'sayulita',
    null,
    'About Sayulita',
    'Sayulita is a lively surf and beach town known for restaurants, nightlife, boutique hotels, vacation rentals, and a strong visitor economy. Housing stock includes homes, villas, condos, and rental properties, attracting investors, lifestyle buyers, surfers, and second-home owners.',
    1,
    true
),
(
    'description',
    'area',
    'cabo-correntes',
    'sierra-madre-jalisco',
    'cabo-correntes',
    null,
    'About Cabo Correntes',
    'Cabo Correntes offers rugged coastline, rural communities, beaches, and mountain scenery south of Puerto Vallarta. Housing and land opportunities vary widely, attracting buyers interested in nature, privacy, ecotourism, and long-term lifestyle or investment potential.',
    1,
    true
),
(
    'description',
    'area',
    'costa-alegre',
    'sierra-madre-jalisco',
    'costa-alegre',
    null,
    'About Costa Alegre',
    'Costa Alegre is a scenic coastal region south of Puerto Vallarta known for beaches, luxury enclaves, ecological reserves, and lower-density development. Buyers are often drawn to privacy, natural beauty, beachfront or view properties, and long-term growth potential.',
    1,
    true
),
(
    'description',
    'area',
    'el-tuito',
    'sierra-madre-jalisco',
    'el-tuito',
    null,
    'About El Tuito',
    'El Tuito is a mountain town south of Puerto Vallarta with a traditional village feel, cooler climate, local restaurants, and rural surroundings. Housing tends toward homes, ranch-style properties, and land, appealing to buyers seeking space, authenticity, and a quieter lifestyle away from the beach.',
    1,
    true
),
(
    'description',
    'area',
    'sierra-madre',
    'sierra-madre-jalisco',
    'sierra-madre',
    null,
    'About Sierra Madre',
    'The Sierra Madre area includes mountain and rural communities with natural scenery, privacy, and a slower pace than the coastal markets. Housing stock varies from homes and ranch properties to land opportunities, attracting buyers interested in nature, space, and long-term lifestyle use.',
    1,
    true
),
(
    'description',
    'area',
    'tomatlan',
    'sierra-madre-jalisco',
    'tomatlan',
    null,
    'About Tomatlan',
    'Tomatlan is a rural and coastal municipality south of Puerto Vallarta with agricultural areas, beaches, and emerging long-term development potential. Buyers may be interested in land, ranch properties, beach access, and value compared with more established resort markets.',
    1,
    true
)
on conflict (
    content_type,
    entity_type,
    entity_slug,
    sort_order
)
do update set
    zone_slug = excluded.zone_slug,
    area_slug = excluded.area_slug,
    community_slug = excluded.community_slug,
    title = excluded.title,
    body = excluded.body,
    active_fl = excluded.active_fl,
    updated_dt = current_timestamp;
