    -- SearchPV listing update/change-log support
    -- Review data types before running in production.

    -- 1) Add the new columns to dw.lstng.
    -- NOTE: Postgres folds unquoted identifiers to lowercase. Use lowercase column names.

    ALTER TABLE dw.lstng
        ADD COLUMN IF NOT EXISTS adrs_st_nm text,
        ADD COLUMN IF NOT EXISTS adrs_zip_cd text,
        ADD COLUMN IF NOT EXISTS lstng_cntrct_end_dt date,
        ADD COLUMN IF NOT EXISTS lstng_cntrct_bgn_dt date,
        ADD COLUMN IF NOT EXISTS sold_dt date,
        ADD COLUMN IF NOT EXISTS pndng_dt date,
        ADD COLUMN IF NOT EXISTS flthrgh_dt date,
        ADD COLUMN IF NOT EXISTS last_prprty_stts_chg_dt date,
        ADD COLUMN IF NOT EXISTS wthdrw_dt date,
        ADD COLUMN IF NOT EXISTS cncl_dt date,
        ADD COLUMN IF NOT EXISTS orgnl_prc_am numeric(14,2),
        ADD COLUMN IF NOT EXISTS lst_prc_am numeric(14,2),
        ADD COLUMN IF NOT EXISTS sld_prc_am numeric(14,2),
        ADD COLUMN IF NOT EXISTS fncng_fl text,
        ADD COLUMN IF NOT EXISTS strt_nb text,
        ADD COLUMN IF NOT EXISTS strt_nm text,
        ADD COLUMN IF NOT EXISTS unit_nb text,
        ADD COLUMN IF NOT EXISTS strt_sfx_ds text,
        ADD COLUMN IF NOT EXISTS bdga_deed_fl text,
        ADD COLUMN IF NOT EXISTS prprty_stl_ds text,
        ADD COLUMN IF NOT EXISTS ttl_lvls_nb integer,
        ADD COLUMN IF NOT EXISTS ttl_room_nb integer,
        ADD COLUMN IF NOT EXISTS ttl_bdrm_nb integer,
        ADD COLUMN IF NOT EXISTS ttl_bthrm_nb numeric(10,2),
        ADD COLUMN IF NOT EXISTS ttl_full_bthrm_nb integer,
        ADD COLUMN IF NOT EXISTS tax_id text,
        ADD COLUMN IF NOT EXISTS prdl_id text,
        ADD COLUMN IF NOT EXISTS prkng_ds text,
        ADD COLUMN IF NOT EXISTS mstr_pln_cmnty_fl text,
        ADD COLUMN IF NOT EXISTS lot_m2_nb numeric(14,2),
        ADD COLUMN IF NOT EXISTS ocn_frnt_mtr_nb numeric(14,2),
        ADD COLUMN IF NOT EXISTS units_in_dvlpmnt_nb integer,
        ADD COLUMN IF NOT EXISTS ft2_deck_ptio_nb numeric(14,2),
        ADD COLUMN IF NOT EXISTS m2_deck_ptio_nb numeric(14,2),
        ADD COLUMN IF NOT EXISTS estmtd_dlvry_dt date,
        ADD COLUMN IF NOT EXISTS pre_cnstrctn_fl text,
        ADD COLUMN IF NOT EXISTS pet_frndly_fl text,
        ADD COLUMN IF NOT EXISTS prprty_tax_am numeric(14,2),
        ADD COLUMN IF NOT EXISTS deed_prkng_m2_nb numeric(14,2),
        ADD COLUMN IF NOT EXISTS cnstrctn_mnfst_fl text,
        ADD COLUMN IF NOT EXISTS crnt_lien_ltgtn_fl text,
        ADD COLUMN IF NOT EXISTS adjcnt_to_fdrl_zone_fl text,
        ADD COLUMN IF NOT EXISTS fdrl_zone_cncsn_fl text,
        ADD COLUMN IF NOT EXISTS ctfct_cmrcl_use_fl text,
        ADD COLUMN IF NOT EXISTS flex_room_fl text,
        ADD COLUMN IF NOT EXISTS lstng_prc_mxn_am numeric(14,2),
        ADD COLUMN IF NOT EXISTS dom_nb integer;

